package aplikace;

import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kody.Casovac;
import kody.HlavniTest;

/**
 *
 * @author Duckyta
 */
public class HlavniOkno extends javax.swing.JFrame {
    
    private final Prihlaseni pr = new Prihlaseni();

    public static Casovac casObednavkaVytvor = new Casovac(4);
    public static Casovac casFaktura = new Casovac(1);
    public static Casovac casExpeduj = new Casovac(2);
    public static Casovac casOdepsaniSkladu = new Casovac(3);

    public static Casovac casVypisZbozi = new Casovac(1);

    public static Casovac casTopSklad = new Casovac(2);

    public static Casovac casRazeniZbozi = new Casovac(3);

    public static Casovac casSumTrzba = new Casovac(3);

    public static Casovac casAvgObj = new Casovac(3);

    public static Casovac casInfoZak = new Casovac(2);

    public static Casovac selectCount = new Casovac(1);
    public static Casovac executeCount = new Casovac(1);
    
    public static Casovac nacteniDatDoDb = new Casovac(20);

    public HlavniOkno() {
        initComponents();
        this.setTitle("Aplikace pro testování DS");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        vytvoritDatabaziBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        naplnBtn = new javax.swing.JButton();
        inMemCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        smazDataBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        vyberDatabazeComboBox = new javax.swing.JComboBox<>();
        volbaDatabazeButton = new javax.swing.JButton();
        odpojitBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spusteniBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Vytvořit testovací prostředí: ");

        vytvoritDatabaziBtn.setText("Vytvoř");
        vytvoritDatabaziBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vytvoritDatabaziBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Naplň prostředí daty:");

        naplnBtn.setText("Naplň");
        naplnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naplnBtnActionPerformed(evt);
            }
        });

        inMemCheckBox.setText("In-memory (Oracle, MS SQL)");
        inMemCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inMemCheckBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Smaž testovací data:");

        smazDataBtn.setText("Smaž data");
        smazDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smazDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vytvoritDatabaziBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(naplnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(smazDataBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inMemCheckBox)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vytvoritDatabaziBtn)
                    .addComponent(inMemCheckBox))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(naplnBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smazDataBtn)
                    .addComponent(jLabel2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Výběr databázového systému:");

        vyberDatabazeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle Database", "MS SQL 2016", "MySQL", "PostgreSQL" }));
        vyberDatabazeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberDatabazeComboBoxActionPerformed(evt);
            }
        });

        volbaDatabazeButton.setText("Připojit");
        volbaDatabazeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volbaDatabazeButtonActionPerformed(evt);
            }
        });

        odpojitBtn.setText("Odpojit");
        odpojitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpojitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vyberDatabazeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volbaDatabazeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(odpojitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vyberDatabazeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(volbaDatabazeButton)
                    .addComponent(odpojitBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Spuštění testu:");

        spusteniBtn.setText("Start");
        spusteniBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spusteniBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(spusteniBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spusteniBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volbaDatabazeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volbaDatabazeButtonActionPerformed
        if (vyberDatabazeComboBox.getSelectedIndex() == 0) {
            pr.hideDatabase();
        } else if (vyberDatabazeComboBox.getSelectedIndex() == 2) {
            pr.hideDatabase();
            pr.hideInstance();
        } else {
            pr.hideInstance();
        }
        pr.setVisible(true);
        pr.volba = vyberDatabazeComboBox.getSelectedIndex();

    }//GEN-LAST:event_volbaDatabazeButtonActionPerformed

    private void vyberDatabazeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vyberDatabazeComboBoxActionPerformed

    }//GEN-LAST:event_vyberDatabazeComboBoxActionPerformed

    private void vytvoritDatabaziBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vytvoritDatabaziBtnActionPerformed
        if (vyberDatabazeComboBox.getSelectedIndex() == 0) {
            if (inMemCheckBox.isSelected() == true) {
                try {
                    if (pr.getConnection() != null) {
                        kody.metodyOrcl.createINmemTables(pr.getConnection());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
            } else if (inMemCheckBox.isSelected() == false) {
                try {
                    if (pr.getConnection() != null) {
                        kody.metodyOrcl.createTables(pr.getConnection());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
            }

        } else if (vyberDatabazeComboBox.getSelectedIndex() == 1) {
            if (inMemCheckBox.isSelected() == true) {
                try {
                    if (pr.getConnection() != null) {
                        kody.metodyOstatni.vytvorInMemTabulky(pr.getConnection());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (inMemCheckBox.isSelected() == false) {
                try {
                    if (pr.getConnection() != null) {
                        kody.metodyOstatni.vytvorTabulkyMicrosoftSQL(pr.getConnection());
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else if (vyberDatabazeComboBox.getSelectedIndex() == 2) {
            try {
                if (pr.getConnection() != null) {
                    kody.metodyOstatni.vytvorTabulkyMySQL(pr.getConnection());
                }
            } catch (SQLException ex) {
                Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (vyberDatabazeComboBox.getSelectedIndex() == 3) {
            try {
                if (pr.getConnection() != null) {
                    kody.metodyOstatni.vytvorTabulkyPostgre(pr.getConnection());
                }
            } catch (SQLException ex) {
                Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_vytvoritDatabaziBtnActionPerformed

    private void odpojitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpojitBtnActionPerformed
        try {
            pr.closeConnection();

        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_odpojitBtnActionPerformed

    private void smazDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smazDataBtnActionPerformed
        switch (vyberDatabazeComboBox.getSelectedIndex()) {
            case 0:
                if (inMemCheckBox.isSelected() == true) {
                    try {
                        if (pr.getConnection() != null) {
                            kody.metodyOrcl.dropTables(pr.getConnection());
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(HlavniOkno.class
                                .getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        if (pr.getConnection() != null) {
                            kody.metodyOrcl.dropTables(pr.getConnection());

                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(HlavniOkno.class
                                .getName()).log(Level.SEVERE, null, ex);
                    }
                }
                break;
            case 1:
                try {
                    if (pr.getConnection() != null) {
                        try {
                            kody.metodyOstatni.smazProstresti(pr.getConnection());
                        } catch (SQLException ex) {
                            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 2:
                try {
                    if (pr.getConnection() != null) {
                        try {
                            kody.metodyOstatni.smazProstrestiMySQL(pr.getConnection());
                        } catch (SQLException ex) {
                            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            case 3: {
                try {
                    if (pr.getConnection() != null) {
                        pr.conn.close();
                        Class.forName("org.postgresql.Driver");
                        String url = "jdbc:postgresql://";
                        url += pr.postgreServer;
                        url += ":";
                        url += pr.postgrePort;
                        url += "/";
                        url += pr.postgreDatabaze;
                        String uziv = pr.postgreUziv;
                        String hesl = pr.postgreHesl;
                        pr.conn = DriverManager.getConnection(url, uziv, hesl);
                        kody.metodyOstatni.smazProstrestiPostge(pr.conn);

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;
        }
    }//GEN-LAST:event_smazDataBtnActionPerformed

    private void naplnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naplnBtnActionPerformed
        try {
            if (pr.getConnection() != null) {
                kody.naplneniDaty.napln(pr.getConnection());
            }
        } catch (SQLException | IOException ex) {
            Logger.getLogger(HlavniOkno.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_naplnBtnActionPerformed

    private void inMemCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inMemCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inMemCheckBoxActionPerformed

    private void spusteniBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spusteniBtnActionPerformed
        kody.HlavniTest ht = new HlavniTest(10000);
        try {
            ht.runTest(pr.getConnection());
        } catch (SQLException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HlavniOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spusteniBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavniOkno.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavniOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox inMemCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton naplnBtn;
    private javax.swing.JButton odpojitBtn;
    private javax.swing.JButton smazDataBtn;
    private javax.swing.JButton spusteniBtn;
    private javax.swing.JButton volbaDatabazeButton;
    private javax.swing.JComboBox<String> vyberDatabazeComboBox;
    private javax.swing.JButton vytvoritDatabaziBtn;
    // End of variables declaration//GEN-END:variables
}
